# Versi '3.8' sudah tidak diperlukan di Docker Compose V2+
services:
  portfolio:
    build:
      context: .
      network: host
    network_mode: "host"
    container_name: portfolio-web
    # ports:
    #   - "3000:3000"
    restart: unless-stopped
